In [1]:
import numpy as np

In [5]:
np.shape(np.empty(shape=(64, 10), dtype = np.float32))

(64, 10)

In [6]:
import torch

In [7]:
b = torch.Tensor([[1,2,3],[4,5,6]])

In [10]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
b.shape

torch.Size([2, 3])

In [12]:
index_1 = torch.LongTensor([[0, 1],
                            [2, 0]])
                            
index_2 = torch.LongTensor([[0, 1, 1],
                            [0, 0, 0]])

In [15]:
print( torch.gather(b, dim=1, index= index_1))

tensor([[1., 2.],
        [6., 4.]])


In [14]:
print( torch.gather(b, dim=0, index= index_2))

tensor([[1., 5., 6.],
        [1., 2., 3.]])


In [17]:
import numpy as np
EPSILON_DECAY = 100000
EPSILON_START = 1.0
EPSILON_END = 0.02
TARGET_UPDATE_FREQUENCY = 10

n_epsiode = 5000
n_time_step = 1000

np.interp( 10 * 1000 + 1, [0, EPSILON_DECAY], [EPSILON_START, EPSILON_END])

0.9019902

In [18]:
np.random.choice(10, 15)

array([2, 6, 3, 1, 8, 7, 1, 1, 0, 8, 9, 5, 3, 3, 9])

In [19]:

index = torch.LongTensor([[0,1,2,3]])

In [26]:
torch.LongTensor([0,1,2,3]).unsqueeze(-1)

tensor([[0],
        [1],
        [2],
        [3]])

In [27]:
index.shape

torch.Size([1, 4])